const defaultProducts = [
  {id:'arc',name:'Arc lounge chair',category:'seating',price:890,image:'assets/furniture_1.jpeg',rating:4.8,reviews:[{name:'Maya L.',stars:5,text:'Even better in person. The curve is incredibly comfortable.'},{name:'Jon B.',stars:4,text:'Beautiful proportions and excellent fabric.'}]},
  {id:'oak',name:'Line oak table',category:'tables',price:1240,image:'assets/furniture_2.jpeg',rating:4.9,reviews:[{name:'Ella K.',stars:5,text:'Solid, simple, and the finish is perfect.'}]},
  {id:'lamp',name:'Classic bed frame',category:'beds',price:420,image:'assets/furniture_3.jpeg',rating:4.7,reviews:[{name:'Rae A.',stars:5,text:'Comfort and style for a restful bedroom.'}]},
  {id:'daybed',name:'Lowline daybed',category:'seating',price:1590,image:'assets/furniture_4.jpeg',rating:4.6,reviews:[{name:'Noah P.',stars:5,text:'A proper statement piece.'}]},
  {id:'coffee',name:'Stone coffee table',category:'tables',price:690,image:'assets/furniture_5.jpeg',rating:4.8,reviews:[]},
  {id:'stool',name:'Milo side stool',category:'seating',price:280,image:'assets/furniture_6.jpeg',rating:4.5,reviews:[]}
];
let customProducts = JSON.parse(localStorage.getItem('ff-products') || '[]');
let selectedFilter = 'all', visibleCount = 4, activeProduct = null, pendingStars = 5;
const products = () => [...customProducts, ...defaultProducts];
const starText = n => '★'.repeat(Math.round(n)) + '☆'.repeat(5-Math.round(n));
const countText = p => `${p.reviews.length} ${p.reviews.length===1?'review':'reviews'}`;
function renderProducts(){const grid=document.querySelector('#product-grid'); const filtered=products().filter(p=>selectedFilter==='all'||p.category===selectedFilter); grid.innerHTML=''; filtered.slice(0,visibleCount).forEach(p=>{const node=document.querySelector('#product-template').content.cloneNode(true); node.querySelector('img').src=p.image;node.querySelector('img').alt=p.name;node.querySelector('.product-category').textContent=p.category;node.querySelector('h3').textContent=p.name;node.querySelector('.price').textContent='$'+p.price.toLocaleString();node.querySelector('.stars').textContent=starText(p.rating);node.querySelector('.review-count').textContent=`${p.rating.toFixed(1)} · ${countText(p)}`;node.querySelector('.product-image').onclick=()=>openProduct(p);node.querySelector('.review-count').onclick=()=>openProduct(p);grid.append(node)});document.querySelector('#load-more').style.display=filtered.length>visibleCount?'block':'none'}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{selectedFilter=b.dataset.filter;visibleCount=4;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});
document.querySelector('#load-more').onclick=()=>{visibleCount+=4;renderProducts()};
function openProduct(product){activeProduct=product;pendingStars=5;const comments=product.reviews.map(r=>`<div class="comment"><b>${r.name}</b><span class="comment-stars">${starText(r.stars)}</span><p>${r.text}</p></div>`).join('')||'<p class="comment">No reviews yet — be the first to share your thoughts.</p>';document.querySelector('#modal-content').innerHTML=`<div class="modal-layout"><img src="${product.image}" alt="${product.name}"><section class="modal-info"><p class="eyebrow">${product.category}</p><h2>${product.name}</h2><p class="modal-price">$${product.price.toLocaleString()}</p><div class="stars">${starText(product.rating)} <span style="color:#555;font:12px 'DM Sans'">${product.rating.toFixed(1)} · ${countText(product)}</span></div><hr><h3>Leave a review</h3><form class="review-form" id="review-form"><input required name="reviewer" placeholder="Your name"><div class="star-picker" aria-label="Choose rating">${[1,2,3,4,5].map(n=>`<button type="button" data-stars="${n}" class="${n<=5?'selected':''}">★</button>`).join('')}</div><textarea required name="comment" placeholder="What do you think of this piece?"></textarea><button class="post-btn">Post review</button></form><hr><h3>Community notes</h3><div id="comments">${comments}</div></section></div>`;document.querySelector('#product-modal').showModal();document.querySelectorAll('[data-stars]').forEach(btn=>btn.onclick=()=>{pendingStars=+btn.dataset.stars;document.querySelectorAll('[data-stars]').forEach(x=>x.classList.toggle('selected',+x.dataset.stars<=pendingStars))});document.querySelector('#review-form').onsubmit=submitReview}
function submitReview(e){e.preventDefault();const data=new FormData(e.target);activeProduct.reviews.unshift({name:data.get('reviewer'),stars:pendingStars,text:data.get('comment')});activeProduct.rating=activeProduct.reviews.reduce((s,r)=>s+r.stars,0)/activeProduct.reviews.length;saveCustom();renderProducts();openProduct(activeProduct)}
function saveCustom(){localStorage.setItem('ff-products',JSON.stringify(customProducts))}
document.querySelector('.close-modal').onclick=()=>document.querySelector('#product-modal').close();
document.querySelector('#product-modal').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
document.querySelector('#upload-form').onsubmit=e=>{e.preventDefault();const form=new FormData(e.target), file=form.get('image');const add=(image)=>{customProducts.unshift({id:'user-'+Date.now(),name:form.get('name'),category:form.get('category'),price:Number(form.get('price')),image:image||'assets/furniture_7.jpeg',rating:0,reviews:[]});saveCustom();e.target.reset();document.querySelector('#upload-message').textContent='Your furniture is now in the collection.';selectedFilter='all';visibleCount=4;document.querySelectorAll('.filter').forEach((b,i)=>b.classList.toggle('active',i===0));renderProducts();location.hash='shop'};if(file&&file.size){const reader=new FileReader();reader.onload=()=>add(reader.result);reader.readAsDataURL(file)}else add()};
renderProducts();
